name: Continuous Deployment to Localhost

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ansible Setup
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S ansible-playbook -i hosts setup-system.yml